### ISSUE TITLE
faster replit db wrapper

### ISSUE THREAD

**Issue by thrzl** [terabyte3/repltable#1]
I truly hope that I don't have to create this myself but if I really do I will:

Can anybody recommend any replit db wrappers that are faster than the basic one? It doesn't necessarily have to be complete, it just needs basic set/get. If you can recommend any, that would be quite useful.

**Comment by Paragonii** [comment]
this is all i could find https://replit.com/talk/learn/I-made-a-wrapper-for-your-wrapper-haha/43305/204475 dk if it'll help.

**Comment by thrzl** [comment]
rewritten!
